### PR TITLE
fix: add encode URL to Plausible button

### PR DESCRIPTION
**Pull request by Fatpandac**

### CODE REVIEW

**Review by livid — COMMENTED** [review]
Thanks for the PR.

Can you please give me one example of the domain that needs escaping?

**Comment by Fatpandac** [comment]
`dweb.link/ipns/k51qzi5uqu5dikgvh3al7o5pxsme6j0aw5s2d1qjwcfqi0t5pids772qhq8ohj`
Maybe is my mistake. 😅

**Comment by livid** [comment]
> dweb.link/ipns/k51qzi5uqu5dikgvh3al7o5pxsme6j0aw5s2d1qjwcfqi0t5pids772qhq8ohj

Cool!

In that case, if you want to use Plausible for your site, you can just use its IPNS string as Plausible domain like this:

Screen Shot 2022-08-17 at 10 31 48 PM

**Comment by livid** [comment]
Plausible's domain field works like an ID or tag. It accepts a simple string value like `example.com` or `k51qzi5uqu5dikgvh3al7o5pxsme6j0aw5s2d1qjwcfqi0t5pids772qhq8ohj`, not the whole URL.

**Comment by livid** [comment]
So the domain value you entered will be part of the URL like this:

https://plausible.io/olivida.eth.limo

In the example above, the domain value is `olivida.eth.limo` for https://olivida.eth.limo , but actually, if you use just `olivida.eth`, it would work too. It works like an ID or tag.

**Comment by livid** [comment]
I checked Plausible's docs, and they have an example that included `/` for adding a subfolder.

https://plausible.io/docs/add-website

So I have merged your change. Thanks a lot!

**Comment by livid** [comment]
I merged and tested. It is working with `/` now.

Thanks again!

Screen Shot 2022-08-17 at 11 09 50 PM

**Pull request merged**
